"""empty message

Revision ID: f78232b3c35e
Revises: a5cffa318ac2
Create Date: 2025-06-02 21:29:28.918794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78232b3c35e'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_from_ID', sa.Integer(), nullable=False),
    sa.Column('user_to_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_ID'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_ID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_ID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(length=250), nullable=False),
    sa.Column('autor_ID', sa.Integer(), nullable=False),
    sa.Column('post_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_ID'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_ID'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.Column('post_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_ID'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('fist_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['user_name'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('last_name')
        batch_op.drop_column('fist_name')
        batch_op.drop_column('user_name')

    op.drop_table('media')
    op.drop_table('comment')
    op.drop_table('post')
    op.drop_table('follower')
    # ### end Alembic commands ###
